### ISSUE TITLE
UnboundLocalError: local variable 'outputdir' referenced before assignment

### ISSUE THREAD

**Issue by Sundyo** [khaled-rahman/SMU#1]
(keyword_extraction) E:\BatchLayout-master\BatchLayoutCode>python runBatchLayout.py -inf ./datasets/input/3elt_dual.mtx -outd ./datasets/output/ -iter 600 -threads 4

@@@@@                   @      @
@    @                  @      @
@  @   @@@@@@ @  @@@@@@ @      @      @@@@@@ @    @ @@@@@@ @    @ @
@@@         @ @@ @    @ @@@@@@ @           @ @    @ @    @ @    @ @@
@  @   @@@@@@ @  @      @    @ @      @@@@@@ @@@@@@ @    @ @    @ @
@    @ @    @ @  @      @    @ @      @    @      @ @    @ @    @ @
@@@@@  @@@@@@ @@ @@@@@@ @    @ @@@@@@ @@@@@@ @@@@@@ @@@@@@ @@@@@@ @@

Running Batchlayout...
./bin/BatchLayout -input ./datasets/input/3elt_dual.mtx -output ./datasets/output/ -iter 600 -batch 256 -algo 2 -init 0 -threads 4
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Something went wrong in processing !!! Check error message and act accordingly.
Reading coordinates file...
Traceback (most recent call last):
  File "runBatchLayout.py", line 130, in <module>
    X = readCoordinates(outputdirector)
  File "runBatchLayout.py", line 62, in readCoordinates
    corfile = open(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType

(keyword_extraction) E:\BatchLayout-master\BatchLayoutCode>python runBatchLayout.py -inf ./datasets/input/3elt_dual.mtx -outd ./datasets/output/ -iter 600 -threads 4

@@@@@                   @      @
@    @                  @      @
@  @   @@@@@@ @  @@@@@@ @      @      @@@@@@ @    @ @@@@@@ @    @ @
@@@         @ @@ @    @ @@@@@@ @           @ @    @ @    @ @    @ @@
@  @   @@@@@@ @  @      @    @ @      @@@@@@ @@@@@@ @    @ @    @ @
@    @ @    @ @  @      @    @ @      @    @      @ @    @ @    @ @
@@@@@  @@@@@@ @@ @@@@@@ @    @ @@@@@@ @@@@@@ @@@@@@ @@@@@@ @@@@@@ @@

Running Batchlayout...
./bin/BatchLayout -input ./datasets/input/3elt_dual.mtx -output ./datasets/output/ -iter 600 -batch 256 -algo 2 -init 0 -threads 4
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Something went wrong in processing !!! Check error message and act accordingly.
Traceback (most recent call last):
  File "runBatchLayout.py", line 128, in <module>
    outputdirector = runBatchLayout(inputfile, outputfile, iteration, batch, algo, init, initf, threads, barnesth, energyth, weight)
  File "runBatchLayout.py", line 59, in runBatchLayout
    return outputdir
UnboundLocalError: local variable 'outputdir' referenced before assignment

**Comment by HC-teemo** [comment]
你使用gcc编译了吗？我在Window上编译运行也遇到过一些错误，建议你去Linux或者macos跑。
Have you compiled with GCC? I also encountered some errors when compiling and running in Windows. I suggest you run on Linux or Mac OS.

**Comment by khaled-rahman** [comment]
@Sundyo, we compiled and ran on Linux and Mac OS. If you want to run it on Windows, I would recommend using Cygwin.
Then, build the software with GCC and run the python file. Please let me know if you have any questions.
