### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by HC-teemo** [khaled-rahman/SMU#2]
Hello, I changed the first line of the test file from `10 10 13` to `12 12 13`. This means that I've added two nodes that are not connected to other nodes. Then，I got this error when run the algorithm.

> Reading input matrices in text (ascii)... 
Input File Directory:./datasets/input/test.mtx
Matrix is symmetric
Converting matrix data from ASCII to COO format: 9.012105874717236e-05 seconds
Input Matrix: Rows = 12, Columns= 12, nnz = 26
Converting to csc ... 
Segmentation fault (core dumped)

I suspect this is because the graph represented by the matrix is not connected graph. But when I changed the first line to `11 11 13`, the algorithm runs successfully.
>Reading input matrices in text (ascii)... 
Input File Directory:./datasets/input/test.mtx
Matrix is symmetric
Converting matrix data from ASCII to COO format: 0.0001745698973536491 seconds
Input Matrix: Rows = 11, Columns= 11, nnz = 26
Converting to csc ... 
80%% - 20%% BH - CB
BH-CACHE Approximation Energy:114.692
BH-CACHE Approximation Wall time required:0.0212087
Creating output file in following directory:./datasets/output/test.mtxBCAPPROX32PARAOUT600.txt

So what's the reason for this error. And how to deal with unconnected graphs with this algorithm.
Thank you very much!

**Comment by khaled-rahman** [comment]
@HC-teemo, BatchLayout works with the connected graphs. But if you have a disconnected graph, the burneshut tree building may fail. For unconnected graphs, you can use the cache-blocking option such as `-algo 2`. We considered the largest component when worked on the largest component.

**Comment by HC-teemo** [comment]
ok, thanks!
